# Generated by Django 4.2.3 on 2023-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="citizen_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_type", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                ("media", models.FileField(upload_to=None)),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=254)),
                ("number", models.IntegerField(null=True)),
                ("address", models.TextField(default="")),
            ],
        ),
    ]
